Algoritmo "atividade8"
// 
//  
// Descrição   : Pegando Celsius e transformando para Farenheits
// Autor(a)    : Diandro Felipe
// Data atual  : 03/08/2026
Var
// Seção de Declarações das variáveis 
   Celsius, Farenheits: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Informe a temperatura em graus Celsius: ")
   leia(Celsius)
   
   Farenheits <- (Celsius*9/5)+32
   escreval("O valor informado em Celsius é: ", Celsius)
   escreval("O valor convertido para Farenheits é: ", Farenheits)
Fimalgoritmo