Algoritmo "Dobrodonumero"
// 
//  
// Descrição   : Ler um numero e exibir o dobro
// Autor(a)    : Diandro FElipe
// Data atual  : 03/08/2026
Var
// Seção de Declarações das variáveis 
  numero, dobro: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreval("informe um numero inteiro: ")
  leia(numero)
  
  dobro <- numero*2
  escreval("Você digitou numero: ", numero)
  escreval("O dobro dele é: ", dobro)
  
Fimalgoritmo