Algoritmo "atividade12"
// 
//  
// Descrição   : contagem de ano novo (descrescente)
// Autor(a)    : Diandro Felipe
// Data atual  : 04/08/2026
Var
// Seção de Declarações das variáveis 
   i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para i de 10 até  1 passo -1 faca
        escreval(i)
   fimpara
   
   escreval("Feliz Ano Novo!!!")

Fimalgoritmo