Algoritmo "exercicio3"
// 
//  
// Descrição   : ler duas notas e informar a média aritmetica
// Autor(a)    : Diandro Felipe
// Data atual  : 03/08/2026
Var
// Seção de Declarações das variáveis 
     numero1,numero2: real
     media: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     escreval("Informe a nota 1: ")
     leia(numero1)
     escreval("Informe a nota2: ")
     leia(numero2)

     media <- (numero1+numero2)/2
     escreval("A nota 1 informada foi: ", numero1)
     escreval("A nota2 informada foi: ", numero2)
     escreval("A média das notas é: ", media)
Fimalgoritmo
